### ISSUE TITLE
App suggestions

### ISSUE THREAD

**Issue by roshavagarga** [TheEvilSkeleton/awesome-android#12]
Cool reader - https://f-droid.org/packages/com.github.axet.bookreader/
Shosetsu - https://f-droid.org/packages/com.github.doomsdayrs.apps.shosetsu/

**Comment by TheEvilSkeleton** [comment]
Alright, it has been done. Thank you. [#e7e5007](https://github.com/TheEvilSkeleton/awesome-android/commit/e7e5007f09ca765e33d0590e7c9f8a07f982d3c4)
